name: saludo
env:
  GLOBAL_DATA: "dato global"

on:
  push:
    branches:
      - main

jobs:
  saludar-job:
    runs-on: ubuntu-latest

    steps:
      - name: mostrar saludo
        run: echo "Hola desde la terminal."
        
      - name: mostrar perfil
        run: | 
          echo " author: ${{ github.actor }} "
          echo " evento: ${{ github.event_name }} "
          echo " repo: ${{ github.repository }} "
          echo " ref: ${{ github.ref_name }} "

      - name: mostrar perfil con env
        env:
          USUARIO_ACTUAL: ${{ github.actor }}
        run: |
          echo " 1 autor: $USUARIO_ACTUAL "
          echo " 1 autor: ${{ github.actor }} "
          echo "2 evento: ${{ github.event_name }}"
          echo "3 repo: ${{ github.repository }}"
          echo "4 ref: ${{ github.ref_name }}"
          echo "5 global: $GLOBAL_DATA "

      - name: condicion 1
        if: github.event_name == 'push'
        run: echo "evento push activado."

      - name: condicion 2
        if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        run: echo "evento pull request activado hacia main."


          
        

